export const RESEARCH_DEMO_STATS = [
  ['1,248', 'Research Papers'],
  ['326', 'Case Studies'],
  ['184', 'Policy Studies'],
  ['97', 'GIS Studies'],
  ['68', 'Citizen Evidence Studies'],
];

export const RESEARCH_DEMO_RECORDS = [
  {
    _id: 'RES-001',
    researchId: 'RES-001',
    title: 'Digital Evidence for Sustainable Land-Use Governance',
    authors: [{ name: 'Aren Veyra' }, { name: 'Mira Solven' }, { name: 'Kavin Ardent' }],
    abstract: 'This fictional demonstration study explores how citizen-submitted land observations, photographs, geographic coordinates, survey observations, and GIS information can be combined to identify land-use patterns and generate structured evidence for land-governance research and policy-support analysis.',
    keywords: ['land governance', 'GIS', 'citizen evidence', 'land use', 'policy'],
    category: 'Land Governance & Policy',
    domain: ['Land Governance', 'GIS', 'Citizen Evidence'],
    researchType: 'Research Paper',
    studyArea: 'Navira Valley Demonstration Region',
    state: 'Demo Study Area',
    district: 'Navira Valley (Fictional)',
    publicationYear: 2026,
    methodology: 'Spatial + Descriptive Analysis',
    dataSources: ['Citizen Evidence', 'Photographs', 'GIS', 'Survey'],
    evidenceStatus: 'Demo - preliminary screening',
    datasetId: 'DATA-001',
    gisLayerId: 'GIS-001',
    findings: 'DEMO / FICTIONAL: Agricultural land conversion was the largest reported category in the simulated evidence set, requiring further verification before any administrative action.',
    isDemoData: true,
  },
  {
    _id: 'RES-002',
    researchId: 'RES-002',
    title: 'Spatial Patterns of Agricultural Land Conversion',
    authors: [{ name: 'Tarin Voss' }, { name: 'Elian Meru' }],
    abstract: 'A fictional spatial analysis of reported agricultural land conversion around the Navira Valley settlement edge using mapped observations, photographs, and a demonstration land-use layer.',
    keywords: ['agriculture', 'GIS', 'land conversion', 'spatial analysis'],
    category: 'Land-Use Change',
    domain: ['Land-Use Change', 'GIS & Remote Sensing', 'Agriculture'],
    researchType: 'GIS Study',
    studyArea: 'Navira Valley Demonstration Region',
    publicationYear: 2026,
    methodology: 'Spatial Analysis',
    dataSources: ['Citizen Evidence', 'GIS', 'Photographs'],
    evidenceStatus: 'Demo - reported observations',
    datasetId: 'DATA-002',
    gisLayerId: 'GIS-002',
    isDemoData: true,
  },
  {
    _id: 'RES-003',
    researchId: 'RES-003',
    title: 'Citizen Participation in Digital Land Monitoring',
    authors: [{ name: 'Sela Noren' }, { name: 'Orin Vale' }],
    abstract: 'This fictional survey study examines how residents could contribute structured observations to a digital land-monitoring workflow and receive status updates after submission.',
    keywords: ['citizen science', 'land monitoring', 'digital evidence'],
    category: 'Citizen Participation',
    domain: ['Citizen Participation', 'Land Governance'],
    researchType: 'Survey Study',
    studyArea: 'Navira Valley Demonstration Region',
    publicationYear: 2026,
    methodology: 'Survey Analysis',
    dataSources: ['Citizen Evidence', 'Survey'],
    evidenceStatus: 'Demo - participation signals',
    datasetId: 'DATA-003',
    gisLayerId: 'GIS-003',
    isDemoData: true,
  },
  {
    _id: 'RES-004',
    researchId: 'RES-004',
    title: 'GIS-Based Urban Expansion and Infrastructure Pressure',
    authors: [{ name: 'Jora Pell' }, { name: 'Nivan Crest' }],
    abstract: 'A fictional GIS assessment of urban expansion signals and infrastructure pressure along the demonstration region transport corridor, using mapped records and land-use categories.',
    keywords: ['urban growth', 'infrastructure', 'GIS', 'land use'],
    category: 'Urban Development',
    domain: ['Urban Development', 'Infrastructure', 'GIS & Remote Sensing'],
    researchType: 'Technical Report',
    studyArea: 'Navira Valley Demonstration Region',
    publicationYear: 2026,
    methodology: 'Mixed Methods',
    dataSources: ['GIS', 'Land Records', 'Statistical Data'],
    evidenceStatus: 'Demo - pattern screening',
    datasetId: 'DATA-004',
    gisLayerId: 'GIS-004',
    isDemoData: true,
  },
];

export const RESEARCH_FILTERS = {
  researchType: ['Research Paper', 'Case Study', 'Survey Study', 'GIS Study', 'Policy Analysis', 'Technical Report', 'Working Paper'],
  domain: ['Land Governance', 'Land Records', 'Land-Use Change', 'Agriculture', 'Urban Development', 'Forest', 'Water Resources', 'Infrastructure', 'Climate & Environment', 'Land Disputes', 'GIS & Remote Sensing', 'Policy & Governance', 'Citizen Participation'],
  dataType: ['Citizen Evidence', 'GIS', 'Survey', 'Satellite', 'Land Records', 'Statistical Data', 'Photographs'],
  methodology: ['Spatial Analysis', 'Statistical Analysis', 'Survey Analysis', 'Comparative Analysis', 'Qualitative Analysis', 'Mixed Methods'],
  year: ['2026', '2025', '2024', '2023', 'Before 2023'],
};

export const RESEARCH_RESULT_ROWS = [
  ['Agricultural Land Conversion', 380, 31.7],
  ['Unauthorized Land-Use Change', 290, 24.2],
  ['Water-Body Encroachment', 202, 16.8],
  ['Disputed / Unclear Land Information', 169, 14.1],
  ['Infrastructure-Related Issues', 159, 13.2],
];

export const RESEARCH_VERIFICATION_ROWS = [
  ['Submitted', 260, 21.7],
  ['Under Review', 310, 25.8],
  ['Partially Verified', 240, 20.0],
  ['Verified', 330, 27.5],
  ['Requires Further Investigation', 60, 5.0],
];

export const getDemoResearch = (id) => RESEARCH_DEMO_RECORDS.find((item) => item._id === id) || RESEARCH_DEMO_RECORDS[0];
